feat: Adding chat store init methods.
googleapis/llama-index-alloydb-pg-python pull request #29
Opened 2024-12-04 05:51 UTC by dishaprakash

feat: Adding chat store init methods.

2024-12-05 17:45 UTC, vishwarajanand approved these changes
LGTM

2024-12-05 18:20 UTC, averikitsch commented on src/llama_index_alloydb_pg/engine.py
> +            messages JSON[] NOT NULL,
Message is just JSON not an array.

2024-12-05 18:21 UTC, averikitsch commented on src/llama_index_alloydb_pg/engine.py
> +            CONSTRAINT "{table_name}_unique_key" UNIQUE (key)
The key will not be unique. Each key will have mulitple rows with 1 message per row with an unique id for ordering

2024-12-05 18:25 UTC, averikitsch requested changes

2024-12-05 18:25 UTC, averikitsch commented on src/llama_index_alloydb_pg/engine.py
> +            messages JSON[] NOT NULL,
This should be message not messages. Message is just JSON not an array.

2024-12-09 22:48 UTC, averikitsch approved these changes

2024-12-09 22:55 UTC, merged